Check whether Redis and database can be connected before tests
carlocorradini/graphmarket pull request #102
Opened 2020-12-12 14:37 UTC by andreastedile

For example, if Redis cannot be connected, the output will be as follows:

Error while connecting to Redis
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
npm ERR! Test failed.  See above for more details.

Signed-off-by: Andrea Stedile <andrea.stedile@studenti.unitn.it>

2020-12-12 14:38 UTC, andreastedile commented
Che ne pensi carlo? L'unica cosa è che ESLint dà questi warning:
Unexpected console statement.(no-console)

2020-12-12 17:48 UTC, carlocorradini commented on tests/globalSetup.ts
> +      resolve(undefined);
metti solo ```resolve()```

2020-12-12 17:48 UTC, carlocorradini commented on tests/globalSetup.ts
> +async function testRedis() {
```async function testRedis(): Promise<void>```

Valore di ritorno ```void```

2020-12-12 17:49 UTC, carlocorradini commented on tests/globalSetup.ts
> +async function testDatabase() {
```async function testDatabase(): Promise<void>```

Valore di ritorno ```void```

2020-12-12 17:49 UTC, carlocorradini commented on tests/globalSetup.ts
> +        resolve(undefined);
```resolve()```

2020-12-12 17:50 UTC, carlocorradini commented on tests/globalSetup.ts
> +          ssl: false,
SSL prendilo dal config (non si sa mai che potremo utilizzare un db "secure".

2020-12-12 17:51 UTC, carlocorradini commented on tests/globalSetup.ts
> +    console.log('Redis can be connected.');
utilizza il logger di app e metti DEBUG  o un valore comodo

2020-12-12 17:51 UTC, carlocorradini commented on tests/globalSetup.ts
> +    console.log('Database can be connected');
Come sopra

2020-12-12 17:52 UTC, carlocorradini requested changes
Guarda i commenti che ho messo

2020-12-12 17:52 UTC, carlocorradini commented
> Che ne pensi carlo? L'unica cosa è che ESLint dà questi warning:
> Unexpected console statement.(no-console)

L'idea comunque e' molto bella ci sta!

2020-12-12 23:06 UTC, carlocorradini requested changes

2020-12-12 23:06 UTC, carlocorradini commented on src/logger/logger.ts
>      ...(EnvUtil.isDevelopment() ? [consoleTransport] : []),
```...(EnvUtil.isDevelopment() || EnvUtil.isTest() ? [consoleTransport] : [])```

2020-12-14 11:14 UTC, carlocorradini approved these changes

2020-12-14 11:24 UTC, merged